import {
	NEXRAD_PRODUCT_BASEREF_0_5,
	NEXRAD_PRODUCT_BASEREF_1_5,
	NEXRAD_PRODUCT_BASEREF_2_5,
	NEXRAD_PRODUCT_BASEREF_3_5,
	NEXRAD_PRODUCT_BASEVEL_0_5,
	NEXRAD_PRODUCT_BASEVEL_1_5,
	NEXRAD_PRODUCT_BASEVEL_2_5,
	NEXRAD_PRODUCT_BASEVEL_3_5,
	NEXRAD_PRODUCT_COEFFICIENT_0_5,
	NEXRAD_PRODUCT_COEFFICIENT_1_5,
	NEXRAD_PRODUCT_COEFFICIENT_2_5,
	NEXRAD_PRODUCT_COEFFICIENT_3_5,
	NEXRAD_PRODUCT_DIGITALREF_0_5,
	NEXRAD_PRODUCT_DIGITALREF_1_5,
	NEXRAD_PRODUCT_DIGITALREF_2_5,
	NEXRAD_PRODUCT_DIGITALREF_3_5,
	NEXRAD_PRODUCT_ECHOTOPS,
	NEXRAD_PRODUCT_HYDROCLASS,
	NEXRAD_PRODUCT_PHASE_0_5,
	NEXRAD_PRODUCT_PHASE_1_5,
	NEXRAD_PRODUCT_PHASE_2_5,
	NEXRAD_PRODUCT_PHASE_3_5,
	NEXRAD_PRODUCT_STORMVEL_0_5,
	NEXRAD_PRODUCT_VADPROFILE,
	NEXRAD_PRODUCT_VERTICALLIQUID,
} from '@/data/nexrad/products'

import {
	SOUNDING_PRODUCT_HODO,
	SOUNDING_PRODUCT_SHARPPY,
	SOUNDING_PRODUCT_SKEWT,
	SOUNDING_PRODUCT_STUVE,
	SOUNDING_PRODUCT_TEXT,
} from '@/data/analysis/soundings/products'

import {
	SURFACE_PRODUCT_FRONTS,
	SURFACE_PRODUCT_MOISTURE_DIVERGENCE,
	SURFACE_PRODUCT_PDF,
	SURFACE_PRODUCT_PRESSURE_FALLS,
	SURFACE_PRODUCT_RAW,
	SURFACE_PRODUCT_TEMPERATURE_SLP,
	SURFACE_PRODUCT_THETAE,
} from '@/data/analysis/surface/products'
import {
	UPPERAIR_LEVEL_250,
	UPPERAIR_LEVEL_300,
	UPPERAIR_LEVEL_500,
	UPPERAIR_LEVEL_700,
	UPPERAIR_LEVEL_850,
	UPPERAIR_LEVEL_925,
	UPPERAIR_LEVEL_CONTOUR,
} from '@/data/analysis/upper-air/levels'
import {
	UPPERAIR_PRODUCT_CAPE,
	UPPERAIR_PRODUCT_DELTAT,
	UPPERAIR_PRODUCT_DELTAZ,
	UPPERAIR_PRODUCT_DEWPOINT,
	UPPERAIR_PRODUCT_JET,
	UPPERAIR_PRODUCT_PDF,
	UPPERAIR_PRODUCT_PRECIP_WATERS,
	UPPERAIR_PRODUCT_RAW,
	UPPERAIR_PRODUCT_REL_HUMIDITY,
	UPPERAIR_PRODUCT_SHEAR,
	UPPERAIR_PRODUCT_THETAE,
	UPPERAIR_PRODUCT_THICKNESS,
	UPPERAIR_PRODUCT_VORTICITY,
} from '@/data/analysis/upper-air/products'

import {
	RAPMESO_PRODUCT_300_DIVERGENCE,
	RAPMESO_PRODUCT_300_JET_ANALYSIS,
	RAPMESO_PRODUCT_500_700_AVG_QV_DIVERGENCE,
	RAPMESO_PRODUCT_500_850_CROSSOVER,
	RAPMESO_PRODUCT_500_JET_ANALYSIS,
	RAPMESO_PRODUCT_500_VORTICITY_ADVECTION,
	RAPMESO_PRODUCT_700_FRONTOGENESIS,
	RAPMESO_PRODUCT_700_RELATIVE_HUMIDITY,
	RAPMESO_PRODUCT_700_VORTICITY_ADVECTION,
	RAPMESO_PRODUCT_850_JET_ANALYSIS,
	RAPMESO_PRODUCT_850_MOISTURE_ADVECTION,
	RAPMESO_PRODUCT_850_TEMPERATURE_ADVECTION,
	RAPMESO_PRODUCT_TRENBERTH_FORCING,
	RAPMESO_PRODUCT_WATER_VAPOR_VORTICITY,
} from '@/data/analysis/rap-mesoanalysis/products'

import {
	ISENTROPIC_PRODUCT_280K,
	ISENTROPIC_PRODUCT_285K,
	ISENTROPIC_PRODUCT_290K,
	ISENTROPIC_PRODUCT_295K,
	ISENTROPIC_PRODUCT_300K,
	ISENTROPIC_PRODUCT_305K,
	ISENTROPIC_PRODUCT_310K,
} from '@/data/analysis/isentropic/products'

export const getSoundingPageIdByProductId = (productId) => {
	switch (productId) {
		case SOUNDING_PRODUCT_SKEWT:
			return 13
		case SOUNDING_PRODUCT_STUVE:
			return 15
		case SOUNDING_PRODUCT_SHARPPY:
			return 14
		case SOUNDING_PRODUCT_TEXT:
			return 147
		case SOUNDING_PRODUCT_HODO:
			return 16
		default:
			return null
	}
}

export const getSurfacePageIdByProductId = (productId) => {
	switch (productId) {
		case SURFACE_PRODUCT_FRONTS:
			return 76
		case SURFACE_PRODUCT_PDF:
		case SURFACE_PRODUCT_RAW:
			return 75
		case SURFACE_PRODUCT_MOISTURE_DIVERGENCE:
			return 77
		case SURFACE_PRODUCT_THETAE:
			return 79
		case SURFACE_PRODUCT_TEMPERATURE_SLP:
			return 80
		case SURFACE_PRODUCT_PRESSURE_FALLS:
			return 78
		default:
			return null
	}
}

export const getUpperAirPageIdByProductAndLevelId = (levelId, productId) => {
	switch (levelId) {
		case UPPERAIR_LEVEL_250:
			switch (productId) {
				case UPPERAIR_PRODUCT_JET:
					return 142
				case UPPERAIR_PRODUCT_RAW:
				case UPPERAIR_PRODUCT_PDF:
					return 136
				default:
					return 136
			}
		case UPPERAIR_LEVEL_300:
			switch (productId) {
				case UPPERAIR_PRODUCT_JET:
					return 69
				case UPPERAIR_PRODUCT_RAW:
				case UPPERAIR_PRODUCT_PDF:
					return 137
				default:
					return 137
			}
		case UPPERAIR_LEVEL_500:
			switch (productId) {
				case UPPERAIR_PRODUCT_JET:
					return 70
				case UPPERAIR_PRODUCT_RAW:
				case UPPERAIR_PRODUCT_PDF:
					return 148
				default:
					return 148
			}
		case UPPERAIR_LEVEL_700:
			switch (productId) {
				case UPPERAIR_PRODUCT_JET:
					return 143
				case UPPERAIR_PRODUCT_RAW:
				case UPPERAIR_PRODUCT_PDF:
					return 139
				case UPPERAIR_PRODUCT_REL_HUMIDITY:
					return 84
				default:
					return 139
			}
		case UPPERAIR_LEVEL_850:
			switch (productId) {
				case UPPERAIR_PRODUCT_JET:
					return 144
				case UPPERAIR_PRODUCT_RAW:
				case UPPERAIR_PRODUCT_PDF:
					return 140
				case UPPERAIR_PRODUCT_DEWPOINT:
					return 85
				default:
					return 140
			}
		case UPPERAIR_LEVEL_925:
			switch (productId) {
				case UPPERAIR_PRODUCT_RAW:
				case UPPERAIR_PRODUCT_PDF:
					return 141
				default:
					return 141
			}
		case UPPERAIR_LEVEL_CONTOUR:
			switch (productId) {
				case UPPERAIR_PRODUCT_CAPE:
					return 87
				case UPPERAIR_PRODUCT_DELTAT:
					return 89
				case UPPERAIR_PRODUCT_DELTAZ:
					return 83
				case UPPERAIR_PRODUCT_PRECIP_WATERS:
					return 90
				case UPPERAIR_PRODUCT_SHEAR:
					return 88
				case UPPERAIR_PRODUCT_THETAE:
					return 86
				case UPPERAIR_PRODUCT_THICKNESS:
					return 91
				case UPPERAIR_PRODUCT_VORTICITY:
					return 82
				default:
					return 83
			}
		default:
			return null
	}
}
export const getRAPMesoPageIdByProductId = (productId) => {
	switch (productId) {
		case RAPMESO_PRODUCT_300_DIVERGENCE:
			return 68
		case RAPMESO_PRODUCT_300_JET_ANALYSIS:
			return 69
		case RAPMESO_PRODUCT_500_JET_ANALYSIS:
			return 70
		case RAPMESO_PRODUCT_500_VORTICITY_ADVECTION:
			return 97
		case RAPMESO_PRODUCT_700_RELATIVE_HUMIDITY:
			return 98
		case RAPMESO_PRODUCT_700_VORTICITY_ADVECTION:
			return 149
		case RAPMESO_PRODUCT_700_FRONTOGENESIS:
			return 99
		case RAPMESO_PRODUCT_850_MOISTURE_ADVECTION:
			return 101
		case RAPMESO_PRODUCT_850_TEMPERATURE_ADVECTION:
			return 102
		case RAPMESO_PRODUCT_850_JET_ANALYSIS:
			return 100
		case RAPMESO_PRODUCT_500_850_CROSSOVER:
			return 103
		case RAPMESO_PRODUCT_500_700_AVG_QV_DIVERGENCE:
			return 104
		case RAPMESO_PRODUCT_TRENBERTH_FORCING:
			return 105
		case RAPMESO_PRODUCT_WATER_VAPOR_VORTICITY:
			return 67
		default:
			return null
	}
}

export const getIsentropicPageIdByProductId = (productId) => {
	switch (productId) {
		case ISENTROPIC_PRODUCT_280K:
		case ISENTROPIC_PRODUCT_285K:
		case ISENTROPIC_PRODUCT_290K:
		case ISENTROPIC_PRODUCT_295K:
		case ISENTROPIC_PRODUCT_300K:
		case ISENTROPIC_PRODUCT_305K:
		case ISENTROPIC_PRODUCT_310K:
			return 106
		default:
			return null
	}
}

export const getDataPageIdByProductId = (productId) => {
	switch (productId) {
		case NEXRAD_PRODUCT_BASEREF_0_5:
		case NEXRAD_PRODUCT_BASEREF_1_5:
		case NEXRAD_PRODUCT_BASEREF_2_5:
		case NEXRAD_PRODUCT_BASEREF_3_5:
			return 17
		case NEXRAD_PRODUCT_BASEVEL_0_5:
		case NEXRAD_PRODUCT_BASEVEL_1_5:
		case NEXRAD_PRODUCT_BASEVEL_2_5:
		case NEXRAD_PRODUCT_BASEVEL_3_5:
			return 18
		case NEXRAD_PRODUCT_COEFFICIENT_0_5:
		case NEXRAD_PRODUCT_COEFFICIENT_1_5:
		case NEXRAD_PRODUCT_COEFFICIENT_2_5:
		case NEXRAD_PRODUCT_COEFFICIENT_3_5:
			return 21
		case NEXRAD_PRODUCT_PHASE_0_5:
		case NEXRAD_PRODUCT_PHASE_1_5:
		case NEXRAD_PRODUCT_PHASE_2_5:
		case NEXRAD_PRODUCT_PHASE_3_5:
			return 58
		case NEXRAD_PRODUCT_DIGITALREF_0_5:
		case NEXRAD_PRODUCT_DIGITALREF_1_5:
		case NEXRAD_PRODUCT_DIGITALREF_2_5:
		case NEXRAD_PRODUCT_DIGITALREF_3_5:
			return 20
		case NEXRAD_PRODUCT_STORMVEL_0_5:
			return 19
		case NEXRAD_PRODUCT_VADPROFILE:
			return 63
		case NEXRAD_PRODUCT_ECHOTOPS:
			return 62
		case NEXRAD_PRODUCT_VERTICALLIQUID:
			return 61
		case NEXRAD_PRODUCT_HYDROCLASS:
			return 64
		default:
			return null
	}
}
