import {
	NEXRAD_PRODUCT_BASEREF_0_5,
	NEXRAD_PRODUCT_BASEREF_1_5,
	NEXRAD_PRODUCT_BASEREF_2_5,
	NEXRAD_PRODUCT_BASEREF_3_5,
	NEXRAD_PRODUCT_BASEVEL_0_5,
	NEXRAD_PRODUCT_BASEVEL_1_5,
	NEXRAD_PRODUCT_BASEVEL_2_5,
	NEXRAD_PRODUCT_BASEVEL_3_5,
	NEXRAD_PRODUCT_COEFFICIENT_0_5,
	NEXRAD_PRODUCT_COEFFICIENT_1_5,
	NEXRAD_PRODUCT_COEFFICIENT_2_5,
	NEXRAD_PRODUCT_COEFFICIENT_3_5,
	NEXRAD_PRODUCT_DIGITALREF_0_5,
	NEXRAD_PRODUCT_DIGITALREF_1_5,
	NEXRAD_PRODUCT_DIGITALREF_2_5,
	NEXRAD_PRODUCT_DIGITALREF_3_5,
	NEXRAD_PRODUCT_ECHOTOPS,
	NEXRAD_PRODUCT_HYDROCLASS,
	NEXRAD_PRODUCT_PHASE_0_5,
	NEXRAD_PRODUCT_PHASE_1_5,
	NEXRAD_PRODUCT_PHASE_2_5,
	NEXRAD_PRODUCT_PHASE_3_5,
	NEXRAD_PRODUCT_STORMVEL_0_5,
	NEXRAD_PRODUCT_VADPROFILE,
	NEXRAD_PRODUCT_VERTICALLIQUID,
} from '@/data/nexrad/products'

import {
	SOUNDING_PRODUCT_HODO,
	SOUNDING_PRODUCT_SHARPPY,
	SOUNDING_PRODUCT_SKEWT,
	SOUNDING_PRODUCT_STUVE,
	SOUNDING_PRODUCT_TEXT,
} from '@/data/analysis/soundings/products'

export const getSoundingPageIdByProductId = (productId) => {
	switch (productId) {
		case SOUNDING_PRODUCT_SKEWT:
			return 13
		case SOUNDING_PRODUCT_STUVE:
			return 15
		case SOUNDING_PRODUCT_SHARPPY:
			return 14
		case SOUNDING_PRODUCT_TEXT:
			return 147
		case SOUNDING_PRODUCT_HODO:
			return 16
		default:
			return null
	}
}
export const getDataPageIdByProductId = (productId) => {
	switch (productId) {
		case NEXRAD_PRODUCT_BASEREF_0_5:
		case NEXRAD_PRODUCT_BASEREF_1_5:
		case NEXRAD_PRODUCT_BASEREF_2_5:
		case NEXRAD_PRODUCT_BASEREF_3_5:
			return 17
		case NEXRAD_PRODUCT_BASEVEL_0_5:
		case NEXRAD_PRODUCT_BASEVEL_1_5:
		case NEXRAD_PRODUCT_BASEVEL_2_5:
		case NEXRAD_PRODUCT_BASEVEL_3_5:
			return 18
		case NEXRAD_PRODUCT_COEFFICIENT_0_5:
		case NEXRAD_PRODUCT_COEFFICIENT_1_5:
		case NEXRAD_PRODUCT_COEFFICIENT_2_5:
		case NEXRAD_PRODUCT_COEFFICIENT_3_5:
			return 21
		case NEXRAD_PRODUCT_PHASE_0_5:
		case NEXRAD_PRODUCT_PHASE_1_5:
		case NEXRAD_PRODUCT_PHASE_2_5:
		case NEXRAD_PRODUCT_PHASE_3_5:
			return 58
		case NEXRAD_PRODUCT_DIGITALREF_0_5:
		case NEXRAD_PRODUCT_DIGITALREF_1_5:
		case NEXRAD_PRODUCT_DIGITALREF_2_5:
		case NEXRAD_PRODUCT_DIGITALREF_3_5:
			return 20
		case NEXRAD_PRODUCT_STORMVEL_0_5:
			return 19
		case NEXRAD_PRODUCT_VADPROFILE:
			return 63
		case NEXRAD_PRODUCT_ECHOTOPS:
			return 62
		case NEXRAD_PRODUCT_VERTICALLIQUID:
			return 61
		case NEXRAD_PRODUCT_HYDROCLASS:
			return 64
		default:
			return null
	}
}
